TRAIN:
  WARMUP_EPOCHS: 5
  EPOCHS: 300
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.05
AUG:
  SSL_AUG: True
MODEL:
  TYPE: moby
  NAME: moby__deit_small__odpr02_tdpr0_cm099_ct02_queue4096_proj2_pred2
  MOBY:
    ENCODER: deit_small
    ONLINE_DROP_PATH_RATE: 0.2
    TARGET_DROP_PATH_RATE: 0.0
    CONTRAST_MOMENTUM: 0.99
    CONTRAST_TEMPERATURE: 0.2
    CONTRAST_NUM_NEGATIVE: 4096
    PROJ_NUM_LAYERS: 2
    PRED_NUM_LAYERS: 2